name: Lighthouse CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  lighthouse:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Install Lighthouse CI
        run: npm install -g @lhci/cli@0.12.x
        
      - name: Build project
        run: npm run build
        
      - name: Run Lighthouse CI (Desktop)
        run: lhci autorun --collect.settings.preset=desktop
        env:
          LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}
          
      - name: Run Lighthouse CI (Mobile)
        run: lhci autorun --collect.settings.preset=mobile
        env:
          LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}
          
      - name: Upload Lighthouse results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: lighthouse-results
          path: .lighthouseci/
          retention-days: 30
          
  performance-budget:
    runs-on: ubuntu-latest
    needs: lighthouse
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Check Performance Budget
        run: |
          echo "🚀 Performance Budget Check"
          echo "✅ Core Web Vitals targets:"
          echo "   - LCP: < 2.5s"
          echo "   - FID: < 100ms"
          echo "   - CLS: < 0.1"
          echo "   - FCP: < 2.0s"
          echo "   - TTI: < 3.0s"
          echo ""
          echo "📊 Healthcare-specific requirements:"
          echo "   - Accessibility: > 90%"
          echo "   - Performance: > 80%"
          echo "   - SEO: > 80%"
          echo "   - Best Practices: > 80%"